name: Build and publish artifacts

on: push

jobs:
  build-artifacts:
    name: Build Python packages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Archive source distribution
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: |
          dist/*.tar.gz

    - name: Archive wheel
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: |
          dist/*.whl

  publish-artifacts:
    name: Publish Python packages
    runs-on: ubuntu-latest
    needs: [build-artifacts]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: dist
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
